spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://lioncat-auth
          predicates:
            - Path=/auth/**
        - id: system
          uri: lb://lioncat-system
          predicates:
            - Path=/system/**
        - id: generator
          uri: lb://lioncat-generator
          predicates:
            - Path=/generator/**
  data:
    # redis通用配置 子服务可以自行配置进行覆盖
    redis:
      host: 124.223.91.119
      port: 6379
      # 密码(如没有密码请注释掉)
      #      password: ENC(FUFg3T4NeXEgBqH7/jIaspMsPsQbZMijGqotkgykxBttYd14rL7nf/0Agrnlv2uH)
      database: 0
      timeout: 10s
      ssl: false

# redisson 配置
redisson:
  # redis key前缀
  keyPrefix:
  # 线程池数量
  threads: 4
  # Netty线程池数量
  nettyThreads: 8
  # 单节点配置
  singleServerConfig:
    # 客户端名称
    clientName: ${spring.application.name}
    # 最小空闲连接数
    connectionMinimumIdleSize: 8
    # 连接池大小
    connectionPoolSize: 32
    # 连接空闲超时，单位：毫秒
    idleConnectionTimeout: 10000
    # 命令等待超时，单位：毫秒
    timeout: 3000
    # 发布和订阅连接池大小
    subscriptionConnectionPoolSize: 50

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  jwt-secret-key: mkxniejmlsmfimsineijnfis